In [22]:
import pandas as pd
import numpy as np

In [7]:
def create_polynomial_features(X, degree=2):
    """ Creates the polynomial features
    Args :
    X : A array tensor for the data .
    degree : A intege for the degree of the generated polynomial function.
    """
    X_new = np.array(X)
    for d in range(2, degree+1):
      X_new = np.c_[X_new, np.power(X, d)]

    return X_new

X = np.array([[1], [2], [3]])
print(create_polynomial_features(X))

[[1 1]
 [2 4]
 [3 9]]


In [18]:
def create_polynomial_features(X, degree=2):
    """ Creates the polynomial features
    Args :
    X : A array for the data .
    degree : A intege for the degree of
    the generated polynomial function .
    """
    X_mem = []
    for X_sub in X.T:
        X_new = X_sub
        for d in range(2, degree+1):
            X_new = np.c_[X_new, np.power(X_sub, d)]
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T

X = np.array([[1, 2],[2, 3],[3, 4]])
degree = 2
create_polynomial_features(X, degree=2)

array([[ 1,  1,  2,  4],
       [ 2,  4,  3,  9],
       [ 3,  9,  4, 16]])

In [19]:
def create_polynomial_features(X, degree=2):
    """ Creates the polynomial features
    Args :
    X : A array for the data .
    degree : A intege for the degree of
    the generated polynomial function .
    """
    X_mem = []
    for X_sub in X.T:
        X_sub = X_sub.T
        X_new = X_sub
        for d in range(2, degree+1):
            X_new = np.c_[X_new, np.power(X_sub, d)]
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T

X = np.array([[1, 2],[2, 3],[3, 4]])
degree = 2
create_polynomial_features(X, degree=2)

array([[ 1,  1,  2,  4],
       [ 2,  4,  3,  9],
       [ 3,  9,  4, 16]])

In [20]:
def create_polynomial_features(X, degree=2):
    """ Creates the polynomial features
    Args :
    X : A array for the data .
    degree : A intege for the degree of
    the generated polynomial function .
    """
    X_mem = []
    for X_sub in X.T:
        X_sub = X_sub.T
        X_new = X_sub
        for d in range(2, degree+1):
            X_new = np.c_[X_sub, np.power(X_sub, d)]
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T

X = np.array([[1, 2],[2, 3],[3, 4]])
degree = 2
create_polynomial_features(X, degree=2)

array([[ 1,  1,  2,  4],
       [ 2,  4,  3,  9],
       [ 3,  9,  4, 16]])

In [21]:
def create_polynomial_features(X, degree=2):
    """ Creates the polynomial features
    Args :
    X : A array for the data .
    degree : A intege for the degree of
    the generated polynomial function .
    """
    X_mem = []
    for X_sub in X.T:
        X_sub = X_sub.T
        X_new = X_sub
        for d in range(2, degree+1):
            X_new = np.c_[X_new, np.power(X_sub, d)]
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T

X = np.array([[1, 2],[2, 3],[3, 4]])
degree = 2
create_polynomial_features(X, degree=2)

array([[ 1,  1,  2,  4],
       [ 2,  4,  3,  9],
       [ 3,  9,  4, 16]])

# Load dataset

In [25]:
df = pd.read_csv('SalesPrediction.csv')
df.head()

TV      Radio  Social Media Influencer       Sales
0  16.0   6.566231      2.907983       Mega   54.732757
1  13.0   9.237765      2.409567       Mega   46.677897
2  41.0  15.886446      2.913410       Mega  150.177829
3  83.0  30.020028      6.922304       Mega  298.246340
4  15.0   8.437408      1.405998      Micro   56.594181

# Preprocessing

## One hot encoding for category data

In [26]:
df = pd.get_dummies(df)
df.head()

TV      Radio  Social Media       Sales  Influencer_Macro  \
0  16.0   6.566231      2.907983   54.732757             False   
1  13.0   9.237765      2.409567   46.677897             False   
2  41.0  15.886446      2.913410  150.177829             False   
3  83.0  30.020028      6.922304  298.246340             False   
4  15.0   8.437408      1.405998   56.594181             False   

   Influencer_Mega  Influencer_Micro  Influencer_Nano  
0             True             False            False  
1             True             False            False  
2             True             False            False  
3             True             False            False  
4            False              True            False

In [27]:
# Handle Null values
df = df.fillna(df.mean())

# Get features
X = df[['TV', 'Radio', 'Social Media', 'Influencer_Macro', 'Influencer_Mega', 'Influencer_Micro', 'Influencer_Nano']]
y = df[['Sales']]

# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)


## Feature Scaling

In [29]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_processed = scaler.fit_transform(X_train)
X_test_processed = scaler.fit_transform(X_test)
scaler.mean_[0]

53.850231941683234

## Polynomial Features

In [30]:
from sklearn.preprocessing import PolynomialFeatures

poly_features = PolynomialFeatures(degree=2)
X_train_poly = poly_features.fit_transform(X_train_processed)
X_test_poly = poly_features.transform(X_test_processed)

# Training & Evaluation

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

poly_model = LinearRegression()
poly_model.fit(X_train_poly, y_train)
preds = poly_model.predict(X_test_poly)
r2_score(y_test, preds)

-2.2119776223197106e+21